name: health_sync
description: "Health Sync - Personalized Healthcare Management"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.0
  google_fonts: ^6.2.1
  intl: any
  uuid: ^4.5.1
  mime: ^1.0.6

  image_picker: ^1.1.2
  file_picker: ^8.1.4
  speech_to_text: ^7.3.0
  url_launcher: ^6.3.2
  timeline_tile: ^2.0.0
  crypto: ^3.0.7
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  font_awesome_flutter: ^10.12.0
  carousel_slider: ^5.1.1
  shared_preferences: ^2.5.4
  flutter_gen: ^5.12.0
  phosphor_flutter: ^2.1.0
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo/
    - assets/developers/

